### ISSUE TITLE
`not recognized command error` on Windows

### ISSUE THREAD

**Issue by 0x48piraj** [Azure/hpcpack-acm-cli#1]
#### For Python 3 and 2.7 on Windows: 

![image](https://user-images.githubusercontent.com/5800726/46543394-56d69b00-c8de-11e8-8c63-fd0d1806b0d9.png)

---

As it's a module, I thought prefixing `python -m` will solve the problem but it didn't.

### LOGCAT : 
```

C:\Users\0x48piraj>py -2 -m clusnode
C:\Users\0x48piraj\.windows-build-tools\python27\python.exe: No module named clusnode
```
---

I thought some error must be there so I checked the existence of module by this buggy command and it showed that there exists a package.

### LOGCAT : 

```
C:\Users\0x48piraj>py -2 -m hpc_acm_cli
C:\Users\0x48piraj\.windows-build-tools\python27\python.exe: No module named hpc_acm_cli.__main__; 'hpc_acm_cli' is a package and cannot be directly executed

```

**Comment by 0x48piraj** [comment]
I'm working on this.

**Comment by coin8086** [comment]
@0x48piraj Thanks for your finding. I'm just back to work from a long vacation. I'll look into it later.

**Comment by coin8086** [comment]
@0x48piraj Hi Piyush, thanks a lot for pointing out the problem. However, you should not use the backing modules(clus.py, diag.py, and node.py) directly. Instead, you should use clusrun.exe, clusdiag.exe and clusnode.exe. These commands are compiled at installation time and put in the `Scripts` directory of your Python installation for Windows. Take Python 3.6 for an example, it's `C:\Users\<username>\AppData\Local\Programs\Python\Python36\Scripts`. You need to add this path to the `PATH` environment. I've updated README to reflect this, thanks to you. Let me know if you still have a problem. Thanks.

**Comment by coin8086** [comment]
Please let me know if you still have the problem. Thanks.
